from dotenv import load_dotenv
import os

load_dotenv()

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_MAI_ENDPOINT = os.getenv("AZURE_MAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")
AZURE_OPENAI_VERSION = os.getenv("AZURE_OPENAI_VERSION")
AZURE_MAI_VERSION = os.getenv("AZURE_MAI_VERSION")
AZURE_OPEN_AI_CHAT_DEPLOYMENT_NAME = os.getenv("AZURE_OPEN_AI_CHAT_DEPLOYMENT_NAME")
AZURE_MAI_IMAGE_DEPLOYMENT_NAME = os.getenv("AZURE_MAI_IMAGE_DEPLOYMENT_NAME")
DRY_RUN = os.getenv("DRY_RUN", "false").lower() == "true"